// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'post_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PostModel _$PostModelFromJson(Map<String, dynamic> json) => PostModel(
      acceptAnswerId: json['acceptAnswerId'] as String?,
      accessScope: (json['accessScope'] as num).toInt(),
      atUserList: json['atUserList'] as List<dynamic>,
      atUserVOList: json['atUserVOList'] as List<dynamic>?,
      bestComment: json['bestComment'] as String?,
      category: json['category'] as String,
      commentNum: (json['commentNum'] as num).toInt(),
      componentName: json['componentName'] as String?,
      content: json['content'] as String,
      cover: json['cover'] as String?,
      createTime: DateTime.parse(json['createTime'] as String),
      description: json['description'] as String?,
      editTime: DateTime.parse(json['editTime'] as String),
      externalLink: json['externalLink'] as String?,
      favourNum: (json['favourNum'] as num).toInt(),
      fileList: json['fileList'] as List<dynamic>,
      hasFavour: json['hasFavour'] as bool,
      hasThumb: json['hasThumb'] as bool,
      id: json['id'] as String,
      language: json['language'] as String?,
      needVip: json['needVip'] as bool?,
      pictureList: (json['pictureList'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      plainTextDescription: json['plainTextDescription'] as String?,
      planetPostId: json['planetPostId'] as String?,
      priority: (json['priority'] as num).toInt(),
      relatedId: json['relatedId'] as String?,
      relatedLink: json['relatedLink'] as String?,
      reviewMessage: json['reviewMessage'] as String,
      reviewStatus: (json['reviewStatus'] as num).toInt(),
      reviewTime: DateTime.parse(json['reviewTime'] as String),
      reviewerId: json['reviewerId'] as String?,
      shortLink: json['shortLink'] as String?,
      showPost: (json['showPost'] as num).toInt(),
      status: json['status'] as String?,
      tags: (json['tags'] as List<dynamic>).map((e) => e as String).toList(),
      thumbNum: (json['thumbNum'] as num).toInt(),
      thumbnailCover: json['thumbnailCover'] as String?,
      title: json['title'] as String?,
      updateTime: DateTime.parse(json['updateTime'] as String),
      user: UserModel.fromJson(json['user'] as Map<String, dynamic>),
      userId: json['userId'] as String,
      videoList: json['videoList'] as List<dynamic>,
      viewNum: (json['viewNum'] as num).toInt(),
    );

Map<String, dynamic> _$PostModelToJson(PostModel instance) => <String, dynamic>{
      'acceptAnswerId': instance.acceptAnswerId,
      'accessScope': instance.accessScope,
      'atUserList': instance.atUserList,
      'atUserVOList': instance.atUserVOList,
      'bestComment': instance.bestComment,
      'category': instance.category,
      'commentNum': instance.commentNum,
      'componentName': instance.componentName,
      'content': instance.content,
      'cover': instance.cover,
      'createTime': instance.createTime.toIso8601String(),
      'description': instance.description,
      'editTime': instance.editTime.toIso8601String(),
      'externalLink': instance.externalLink,
      'favourNum': instance.favourNum,
      'fileList': instance.fileList,
      'hasFavour': instance.hasFavour,
      'hasThumb': instance.hasThumb,
      'id': instance.id,
      'language': instance.language,
      'needVip': instance.needVip,
      'pictureList': instance.pictureList,
      'plainTextDescription': instance.plainTextDescription,
      'planetPostId': instance.planetPostId,
      'priority': instance.priority,
      'relatedId': instance.relatedId,
      'relatedLink': instance.relatedLink,
      'reviewMessage': instance.reviewMessage,
      'reviewStatus': instance.reviewStatus,
      'reviewTime': instance.reviewTime.toIso8601String(),
      'reviewerId': instance.reviewerId,
      'shortLink': instance.shortLink,
      'showPost': instance.showPost,
      'status': instance.status,
      'tags': instance.tags,
      'thumbNum': instance.thumbNum,
      'thumbnailCover': instance.thumbnailCover,
      'title': instance.title,
      'updateTime': instance.updateTime.toIso8601String(),
      'user': instance.user,
      'userId': instance.userId,
      'videoList': instance.videoList,
      'viewNum': instance.viewNum,
    };
