// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      id: json['id'] as String,
      planetCode: json['planetCode'] as String?,
      planetPostAuth: (json['planetPostAuth'] as num).toInt(),
      userName: json['userName'] as String,
      userAvatar: json['userAvatar'] as String?,
      userThumbnailAvatar: json['userThumbnailAvatar'] as String?,
      gender: json['gender'] as String?,
      userProfile: json['userProfile'] as String?,
      interests: json['interests'] as String?,
      place: json['place'] as String?,
      school: json['school'] as String?,
      direction: json['direction'] as String?,
      graduationYear: (json['graduationYear'] as num?)?.toInt(),
      company: json['company'] as String?,
      job: json['job'] as String?,
      github: json['github'] as String?,
      blog: json['blog'] as String?,
      score: (json['score'] as num).toInt(),
      jobStatus: json['jobStatus'] as String?,
      scoreLevel: (json['scoreLevel'] as num).toInt(),
      followeeNum: (json['followeeNum'] as num).toInt(),
      followNum: (json['followNum'] as num).toInt(),
      followStatus: (json['followStatus'] as num).toInt(),
      vipExpireTime: json['vipExpireTime'] as String?,
      vipNumber: json['vipNumber'] as String?,
      userRole: json['userRole'] as String,
      scoreRank: (json['scoreRank'] as num?)?.toInt(),
      postAllThumbNum: (json['postAllThumbNum'] as num?)?.toInt(),
      postAllViewNum: (json['postAllViewNum'] as num?)?.toInt(),
      needGuide: (json['needGuide'] as num).toInt(),
      syncPopupLeftCount: (json['syncPopupLeftCount'] as num).toInt(),
      paymentInfo: json['paymentInfo'] as String?,
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'id': instance.id,
      'planetCode': instance.planetCode,
      'planetPostAuth': instance.planetPostAuth,
      'userName': instance.userName,
      'userAvatar': instance.userAvatar,
      'userThumbnailAvatar': instance.userThumbnailAvatar,
      'gender': instance.gender,
      'userProfile': instance.userProfile,
      'interests': instance.interests,
      'place': instance.place,
      'school': instance.school,
      'direction': instance.direction,
      'graduationYear': instance.graduationYear,
      'company': instance.company,
      'job': instance.job,
      'github': instance.github,
      'blog': instance.blog,
      'score': instance.score,
      'jobStatus': instance.jobStatus,
      'scoreLevel': instance.scoreLevel,
      'followeeNum': instance.followeeNum,
      'followNum': instance.followNum,
      'followStatus': instance.followStatus,
      'vipExpireTime': instance.vipExpireTime,
      'vipNumber': instance.vipNumber,
      'userRole': instance.userRole,
      'scoreRank': instance.scoreRank,
      'postAllThumbNum': instance.postAllThumbNum,
      'postAllViewNum': instance.postAllViewNum,
      'needGuide': instance.needGuide,
      'syncPopupLeftCount': instance.syncPopupLeftCount,
      'paymentInfo': instance.paymentInfo,
    };
